apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-demo
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-demo
  template:
    metadata:
      labels:
        app: secret-demo
    spec:
      containers:
      - name: secret-demo
        image: busybox
        command: ["sh", "-c", "echo Username=$APP_USERNAME && echo Password=$APP_PASSWORD && sleep 3600"]
        env:
        - name: APP_USERNAME
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: APP_USERNAME
        - name: APP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: myapp-secret
              key: APP_PASSWORD
