apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  namespace: dev
type: Opaque
stringData:
  APP_USERNAME: admin
  APP_PASSWORD: MyPassword123apiVersion: v1
kind: Secret
metadata:
  name: myapp-secret
  namespace: dev
type: Opaque
stringData:
  APP_USERNAME: "admin"
  APP_PASSWORD: "MyPassword123"
